- name: demo on filters
  hosts: local
  connection: local
  vars:
   topics: linux, shell, ansible, terraform
   course: "DevOps with Ansible"
   myIP: "192.168.1.10"
   tagsmap :
      name: ansible
      project: roboshop
      omponent: catalogue

   tagslist : [
        {
            "key": "name",
            "value": "ansible"
        },
        {
            "key": "project",
            "value": "roboshop"
        },
        {
            "key": "omponent",
            "value": "catalogue"
        }
    ]

  tasks:
  - name: greeting
    ansible.builtin.debug:
      msg: "Hi Sivakumar, {{ Greeting | default('Good Morning') }}"

  - name: convert string to list
    ansible.builtin.debug:
      msg: "{{ topics | split(',') }}"

  - name: convert map to list
    ansible.builtin.debug:
     msg: "{{ tagsmap |dict2items }}" 

     #sg: "{{ tags | dict2items }}"

  - name: convert list to map
    ansible.builtin.debug:
     msg: "{{ tagslist | items2dict }}"

  - name: read student yaml
    ansible.builtin.set_fact: # means setting the variable
      student_yaml: "{{ lookup('file', 'students.yaml' ) | from_yaml }}" 
  - name: convert YAML TO JSON
    ansible.builtin.debug:
     msg: "{{ student_yaml | to_nice_json }}" 

  - name: convert to upper case
    ansible.builtin.debug:
     msg: "{{ course | upper }}"

  - name: convert to lower case
    ansible.builtin.debug:
     msg: "{{ course | lower }}"
     #converstion lower and upper

  - name: check ipv4
    ansible.builtin.debug:
     msg: "{{ myIP | ansible.utils.ipv4 }}"
   #checking ip